#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_hello_world:
    path: /hello/
    controller: App\Controller\HelloController::index

# the "app_lucky_number" route name is not important yet
app_hello_number:
    path: /hello/number
    controller: App\Controller\HelloController::number

